# Ross Jacobs' pre-commit file
fail_fast: false
default_language_version:
  python: python3.7
  system: bash5.0
repos:
  ##########
  # PYTHON #
  ##########
  - repo: https://github.com/doublify/pre-commit-isort
    rev: 8b000d05eb34f1e7d803c43b6b1f224feaa2609c
    hooks:
      - id: isort
        args: ["-ot"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.701
    hooks:
      - id: mypy
  - repo: https://github.com/ambv/black
    rev: cea13f498418784e22f8fbd78db3f9240a2bad11
    hooks:
      - id: black
        args: ["--line-length=79"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      # Python Checks
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      # Fixers
      - id: flake8
      - id: fix-encoding-pragma
      - id: requirements-txt-fixer

  ###########
  # GENERAL #
  ###########
      - id: check-added-large-files
        args: ["--maxkb=10"]
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: name-tests-test
      - id: mixed-line-ending
        args: ["--fix=lf"]
      # Data formats
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: sort-simple-yaml
      # Security
      - id: detect-private-key
      # Project enforcement
      - id: forbid-new-submodules
  - repo: https://github.com/Lucas-C/pre-commit-hooks-go
    rev: f560931e20a207d4037f82fb2765747f670a58ce
    hooks:
      - id: checkmake
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.0
    hooks:
      - id: forbid-binary
      - id: script-must-have-extension

  ########
  # BASH #
  ########
      - id: shellcheck
      - id: shfmt

  ############
  # MARKDOWN #
  ############
  - repo: https://github.com/awebdeveloper/pre-commit-prettier
    rev: c0573b2f7c5f39fddf1c5b8b4528cc73686df524
    hooks:
      - id: prettier
        args: ["--write", "--prose-wrap", "always", "--ignore-path", "<( echo LICENSE.md )"]
        types: [markdown]

  #########
  # C/CPP #
  #########
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v0.2.0
    hooks:
      - id: clang-format
        args: [-i, --style=Google]
      - id: clang-tidy
        args: [-fix, -fix-errors, -checks=*, -warnings-as-errors=*]
      - id: oclint
        args: [-enable-clang-static-analyzer, -enable-global-analysis]
